---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: 5985
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
  - name: windows-2012R2

suites:
  - name: all
    run_list:
      - recipe[vcruntime::vc6]
      - recipe[vcruntime::vc9]
      - recipe[vcruntime::vc10]
      - recipe[vcruntime::vc11]
      - recipe[vcruntime::vc12]
      - recipe[vcruntime::vc14]
      - recipe[vcruntime::vc15]
