driver:
  name: vagrant

transport:
  name: winrm
  elevated: true

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
  - name: windows-2008r2
    driver_config:
      box: chef/windows-server-2008r2-standard
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard

suites:
  - name: all
    run_list:
      - recipe[vcruntime::vc6]
      - recipe[vcruntime::vc9]
      - recipe[vcruntime::vc10]
      - recipe[vcruntime::vc11]
      - recipe[vcruntime::vc12]
      - recipe[vcruntime::vc14]
      - recipe[vcruntime::vc15]
